import jsPDF from 'jspdf';
import logoUrl from '../assets/tcj_logo.png?url';

// ==========================================
// 1. CONFIG & THEME
// ==========================================
const THEME = {
  primary: '#2c3e50',    // Dark Slate Blue (Headers)
  secondary: '#34495e',  // Lighter Blue (Subheaders)
  accent: '#f1f5f9',     // Very Light Grey (Zebra stripes)
  text: '#333333',       // Dark Grey (Body text)
  lightText: '#7f8c8d',  // Grey (Metadata)
  white: '#ffffff',
  line: '#e2e8f0',       // Light border color
};

const LAYOUT = {
  marginX: 15,
  lineHeight: 6,
  headerHeight: 8,
  pageWidth: 210, // A4 width in mm
};

// ==========================================
// 2. HELPERS
// ==========================================

const loadImageAsDataURL = async (url) => {
  try {
    const res = await fetch(url);
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

const formatCurrency = (amount) => {
  const num = Number(amount) || 0;
  return `PHP ${num.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric', month: 'short', day: 'numeric'
  });
};

// Helper: Draw Report Header with Logo and Title
const drawReportHeader = (doc, title, subtitle, adminName, logoDataUrl, storeSettings = {}) => {
  const HEADER_Y = 15;
  const LOGO_WIDTH = 30; 
  const LOGO_HEIGHT = 18;
  const PAGE_WIDTH = doc.internal.pageSize.getWidth();
  let y = HEADER_Y;

  // 1. LEFT COLUMN: Logo
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', LAYOUT.marginX, y, LOGO_WIDTH, LOGO_HEIGHT);
  }
  
  // 2. RIGHT COLUMN: Business Info
  
  // Store Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(THEME.primary);
  doc.text(storeSettings.store_name || 'TJC AUTO SUPPLY', PAGE_WIDTH - LAYOUT.marginX, y + 2, { align: 'right' });
  
  y += 7;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  
  // Address
  doc.text(storeSettings.address || 'San Fernando, Pampanga', PAGE_WIDTH - LAYOUT.marginX, y + 2, { align: 'right' });

  // Contact
  const contactText = `${storeSettings.email || 'N/A'} | ${storeSettings.contact_number || 'N/A'}`;
  doc.text(contactText, PAGE_WIDTH - LAYOUT.marginX, y + 6, { align: 'right' });
  
  // 3. CENTER SECTION: Report Title (Below Logo/Info Block)
  y = Math.max(HEADER_Y + LOGO_HEIGHT + 5, y + 10);
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(THEME.secondary);
  doc.text(title, LAYOUT.marginX, y); 

  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  doc.text(subtitle, LAYOUT.marginX, y); 
  
  y += 5;
  doc.setDrawColor(THEME.line);
  doc.line(LAYOUT.marginX, y, PAGE_WIDTH - LAYOUT.marginX, y); // Separator line
  
  return y + 8; // Return new Y position before the table starts
};


// Helper: Draw Footer
const drawFooter = (doc, adminName) => {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const footerY = 285;

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(THEME.line);
    doc.line(LAYOUT.marginX, footerY - 5, pageWidth - LAYOUT.marginX, footerY - 5);
    
    doc.setFontSize(8);
    doc.setTextColor(THEME.lightText);
    doc.text(`Generated by: ${adminName}`, LAYOUT.marginX, footerY);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, LAYOUT.marginX, footerY + 4);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - LAYOUT.marginX, footerY, { align: 'right' });
  }
};

// ==========================================
// 3. REPORTS (Updated to pass storeSettings)
// ==========================================

// --- SALES REPORT ---
export const generateSalesReportPDF = async (salesData, startDate, endDate, adminName, rangeLabel = 'Daily', storeSettings = {}) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);
  
  // [UPDATED CALL] Pass storeSettings to the header function
  let yPos = drawReportHeader(doc, 'Sales Report', `Period: ${formatDate(startDate)} - ${formatDate(endDate)}`, adminName, logoDataUrl, storeSettings);

  const filteredOrders = salesData || [];
  
  // Flatten for table display
  const flattenedData = filteredOrders.map(order => ({
      date: formatDate(order.orderDate),
      name: order.productName, 
      qty: Number(order.quantity) || 0,
      price: Number(order.unitPrice) || 0,
      total: Number(order.totalPrice) || 0,
      payment: order.paymentMethod || 'Cash',
      status: order.paymentStatus || 'Paid'
  }));

  const cols = {
    date: { x: 15, w: 25 },
    name: { x: 40, w: 60 },
    qty: { x: 105, w: 10 },
    price: { x: 125, w: 20 },
    total: { x: 150, w: 20 },
    pay: { x: 175, w: 15 },
    stat: { x: 195, w: 15 }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F'); 
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    
    doc.text('Date', cols.date.x + 2, y + 5.5);
    doc.text('Product Name', cols.name.x, y + 5.5);
    doc.text('Qty', cols.qty.x, y + 5.5, { align: 'center' });
    doc.text('Price', cols.price.x, y + 5.5, { align: 'right' });
    doc.text('Total', cols.total.x, y + 5.5, { align: 'right' });
    doc.text('Method', cols.pay.x, y + 5.5, { align: 'left' });
    doc.text('Status', cols.stat.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  
  let grandTotal = 0;

  flattenedData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
      doc.setFont('helvetica', 'normal'); 
      doc.setFontSize(8); 
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    doc.setTextColor(THEME.text);
    const name = item.name.length > 35 ? item.name.substring(0, 32) + '...' : item.name;

    doc.text(item.date, cols.date.x + 2, yPos + 5);
    doc.text(name, cols.name.x, yPos + 5);
    doc.text(item.qty.toString(), cols.qty.x, yPos + 5, { align: 'center' });
    doc.text(formatCurrency(item.price).replace('PHP ',''), cols.price.x, yPos + 5, { align: 'right' });
    doc.text(formatCurrency(item.total).replace('PHP ',''), cols.total.x, yPos + 5, { align: 'right' });
    
    doc.text(item.payment.substring(0,8), cols.pay.x, yPos + 5, { align: 'left' });
    
    if(item.status !== 'Paid') doc.setTextColor('#e74c3c'); 
    else doc.setTextColor('#27ae60'); 
    doc.text(item.status, cols.stat.x, yPos + 5, { align: 'right' });

    grandTotal += item.total;
    yPos += 7;
  });

  yPos += 5;
  doc.setDrawColor(THEME.primary);
  doc.setLineWidth(0.5);
  doc.line(130, yPos, 195, yPos); 
  yPos += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(THEME.primary);
  doc.text('Grand Total:', 145, yPos, { align: 'right' });
  doc.text(formatCurrency(grandTotal), 195, yPos, { align: 'right' });

  drawFooter(doc, adminName);
  return doc;
};


// --- INVENTORY REPORT ---
export const generateInventoryReportPDF = async (inventoryData, startDate, endDate, adminName, storeSettings = {}) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);
  
  // [UPDATED CALL] Pass storeSettings to the header function
  let yPos = drawReportHeader(doc, 'Inventory Report', `Status as of: ${formatDate(endDate)}`, adminName, logoDataUrl, storeSettings);

  const cols = {
    name: { x: 15 },
    brand: { x: 80 },
    qty: { x: 120 },
    price: { x: 150 },
    val: { x: 195 }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F');
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    
    doc.text('Product Name', cols.name.x + 2, y + 5.5);
    doc.text('Brand', cols.brand.x, y + 5.5);
    doc.text('Stock', cols.qty.x, y + 5.5, { align: 'center' });
    doc.text('Unit Price', cols.price.x, y + 5.5, { align: 'right' });
    doc.text('Total Value', cols.val.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  let totalInventoryValue = 0;

  inventoryData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    const name = item.productName.length > 35 ? item.productName.substring(0, 32) + '...' : item.productName;
    const value = item.currentStock * item.price;
    totalInventoryValue += value;

    doc.setTextColor(THEME.text);
    doc.setFont('helvetica', 'normal');
    
    doc.text(name, cols.name.x + 2, yPos + 5);
    doc.text(item.brand || '-', cols.brand.x, yPos + 5);
    
    if (item.stockStatus !== 'In Stock') doc.setTextColor('#e74c3c');
    doc.text(item.currentStock.toString(), cols.qty.x, yPos + 5, { align: 'center' });
    
    doc.setTextColor(THEME.text);
    doc.text(formatCurrency(item.price).replace('PHP ',''), cols.price.x, yPos + 5, { align: 'right' });
    doc.text(formatCurrency(value).replace('PHP ',''), cols.val.x, yPos + 5, { align: 'right' });

    yPos += 7;
  });

  yPos += 5;
  doc.setDrawColor(THEME.primary);
  doc.line(130, yPos, 195, yPos);
  yPos += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(THEME.primary);
  doc.text('Total Inventory Asset Value:', 140, yPos, { align: 'right' });
  doc.text(formatCurrency(totalInventoryValue), 195, yPos, { align: 'right' });

  drawFooter(doc, adminName);
  return doc;
};


// --- SMART DEAD STOCK REPORT ---
export const generateDeadStockReportPDF = async (deadStockData, adminName, storeSettings = {}) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);

  // [UPDATED CALL] Pass storeSettings to the header function
  let yPos = drawReportHeader(doc, 'Dead Stock Report', `As of: ${formatDate(new Date())}`, adminName, logoDataUrl, storeSettings);

  const cols = {
    name: { x: 15 },
    category: { x: 95 },
    qty: { x: 135 },
    capital: { x: 165 },
    dormancy: { x: 195 }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F');
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    
    doc.text('Product / Serial Unit', cols.name.x + 2, y + 5.5);
    doc.text('Category', cols.category.x, y + 5.5);
    doc.text('Stock', cols.qty.x, y + 5.5, { align: 'center' });
    doc.text('Tied Capital', cols.capital.x, y + 5.5, { align: 'right' });
    doc.text('Dormancy', cols.dormancy.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;

  let totalTiedCapital = 0;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  deadStockData.forEach((item, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, 7, 'F');
    }

    doc.setTextColor(THEME.text);

    let displayName = item.name;
    if(item.type === 'Serial') {
        displayName += ` (SN: ${item.serialNumber})`;
    }
    if (displayName.length > 45) displayName = displayName.substring(0, 42) + '...';

    doc.text(displayName, cols.name.x + 2, yPos + 5);
    doc.text(item.category || '-', cols.category.x, yPos + 5);
    doc.text(String(item.currentStock), cols.qty.x, yPos + 5, { align: 'center' });
    
    const cap = Number(item.tiedUpValue) || 0;
    totalTiedCapital += cap;
    doc.text(formatCurrency(cap).replace('PHP ',''), cols.capital.x, yPos + 5, { align: 'right' });
    
    const days = String(item.daysDormant).replace(' days', '');
    doc.text(`${days} d`, cols.dormancy.x, yPos + 5, { align: 'right' });

    yPos += 7;
  });

  yPos += 5;
  doc.setDrawColor(THEME.primary);
  doc.line(130, yPos, 195, yPos);
  yPos += 6;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(THEME.primary);
  doc.text('Total Tied Capital:', 155, yPos, { align: 'right' });
  doc.text(formatCurrency(totalTiedCapital), 195, yPos, { align: 'right' });

  drawFooter(doc, adminName);
  return doc;
};


// --- RETURNS REPORT ---
export const generateReturnsReportPDF = async (returnsData, startDate, endDate, adminName, storeSettings = {}) => {
  const doc = new jsPDF();
  const logoDataUrl = await loadImageAsDataURL(logoUrl);

  // [UPDATED CALL] Pass storeSettings to the header function
  let yPos = drawReportHeader(doc, 'Returns Report', `${formatDate(startDate)} - ${formatDate(endDate)}`, adminName, logoDataUrl, storeSettings);

  const cols = {
    id: { x: 15 },
    items: { x: 45 },      // [NEW] Items Column
    customer: { x: 95 },
    reason: { x: 135 },
    amount: { x: 195 }
  };

  const drawHeader = (y) => {
    doc.setFillColor(THEME.primary);
    doc.rect(15, y, 180, 8, 'F');
    doc.setTextColor(THEME.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    
    doc.text('Return ID', cols.id.x + 2, y + 5.5);
    doc.text('Items Returned', cols.items.x, y + 5.5);
    doc.text('Customer', cols.customer.x, y + 5.5);
    doc.text('Reason', cols.reason.x, y + 5.5);
    doc.text('Refund', cols.amount.x, y + 5.5, { align: 'right' });
  };

  drawHeader(yPos);
  yPos += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  let totalRefund = 0;

  returnsData.forEach((item, index) => {
    // 1. Calculate height needed for this row (based on items)
    const itemsList = item.items || [];
    const rowHeight = Math.max(7, (itemsList.length * 4) + 4); 

    // 2. Check Page Break
    if (yPos + rowHeight > 280) {
      doc.addPage();
      yPos = 20;
      drawHeader(yPos);
      yPos += 8;
      doc.setFont('helvetica', 'normal'); 
      doc.setFontSize(8);
    }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, yPos, 180, rowHeight, 'F');
    }

    doc.setTextColor(THEME.text);
    
    // 3. Print Data
    doc.text(`#${item.return_id}`, cols.id.x + 2, yPos + 5);
    
    // Customer
    const customer = item.customer_name?.length > 18 ? item.customer_name.substring(0, 15) + '..' : item.customer_name;
    doc.text(customer, cols.customer.x, yPos + 5);

    // Reason
    doc.text(item.return_reason.substring(0, 20) || 'N/A', cols.reason.x, yPos + 5);
    
    // Amount
    const amt = Number(item.refund_amount) || 0;
    totalRefund += amt;
    doc.text(formatCurrency(amt), cols.amount.x, yPos + 5, { align: 'right' });

    // 4. Print Items Loop
    let itemY = yPos + 5;
    if (itemsList.length > 0) {
        itemsList.forEach(prod => {
            let line = `• ${prod.product_name}`;
            if(prod.serial_numbers) line += ` (SN: ${prod.serial_numbers})`;
            
            // Truncate if too long
            if(line.length > 35) line = line.substring(0, 32) + '...';
            
            doc.text(line, cols.items.x, itemY);
            itemY += 4; // Spacing for next item
        });
    } else {
        doc.text('-', cols.items.x, itemY);
    }

    yPos += rowHeight;
  });

  yPos += 5;
  doc.setFont('helvetica', 'bold');
  doc.text('Total Refunded:', 150, yPos, { align: 'right' });
  doc.text(formatCurrency(totalRefund), 195, yPos, { align: 'right' });

  drawFooter(doc, adminName);
  return doc;
};

// Sale Receipt [FIXED: NOW ACCEPTS storeSettings]
export const generateSaleReceipt = async ({
  saleNumber,
  customerName,
  items = [],
  totalAmount = 0,
  paymentMethod = 'Cash',
  tenderedAmount = 0,
  changeAmount = 0,
  address = '',
  shippingOption = 'In-Store Pickup',
  createdAt = new Date(),
  storeSettings = {} // Added storeSettings parameter
}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  let y = 15;
  
  const logoDataUrl = await loadImageAsDataURL(logoUrl);

  // 1. Header Section
  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 15, y, 25, 18);
  }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(THEME.primary);
  
  // [FIX] Use Store Name from settings or fallback
  doc.text(storeSettings.store_name || 'TJC AUTO SUPPLY', 200, y + 5, { align: 'right' });
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  
  // [FIX] Use Address from settings or fallback
  doc.text(storeSettings.address || 'San Fernando, Pampanga', 200, y + 10, { align: 'right' });
  
  // [FIX] Use Contact Info from settings
  const contactText = `${storeSettings.email || 'tjautosupply@gmail.com'} | ${storeSettings.contact_number || '0912 345 6789'}`;
  doc.text(contactText, 200, y + 15, { align: 'right' });

  y += 30;

  // 2. Invoice Details Box
  doc.setDrawColor(THEME.line);
  doc.setFillColor(THEME.accent);
  doc.roundedRect(15, y, 180, 25, 2, 2, 'F');
  
  doc.setTextColor(THEME.text);
  doc.setFontSize(10);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, y + 6);
  doc.setFont('helvetica', 'normal');
  doc.text(customerName || 'Walk-in Customer', 20, y + 12);
  const addr = address ? address.substring(0, 40) : shippingOption;
  doc.setFontSize(9);
  doc.setTextColor(THEME.lightText);
  doc.text(addr, 20, y + 17);

  doc.setTextColor(THEME.text);
  doc.setFontSize(10);
  
  doc.setFont('helvetica', 'bold');
  doc.text('Receipt #:', 140, y + 6);
  doc.text('Date:', 140, y + 12);
  doc.text('Payment:', 140, y + 18);

  doc.setFont('helvetica', 'normal');
  doc.text(String(saleNumber), 190, y + 6, { align: 'right' });
  doc.text(new Date(createdAt).toLocaleDateString(), 190, y + 12, { align: 'right' });
  doc.text(paymentMethod, 190, y + 18, { align: 'right' });

  y += 35;

  // 3. Item Table
  const cols = {
    desc: { x: 15, w: 90 },
    qty: { x: 130, w: 20 },
    price: { x: 160, w: 25 },
    total: { x: 195, w: 25 }
  };

  doc.setFillColor(THEME.primary);
  doc.rect(15, y, 180, 8, 'F');
  doc.setTextColor(THEME.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Item Description', cols.desc.x + 2, y + 5.5);
  doc.text('Qty', cols.qty.x, y + 5.5, { align: 'center' });
  doc.text('Price', cols.price.x, y + 5.5, { align: 'right' });
  doc.text('Amount', cols.total.x, y + 5.5, { align: 'right' });

  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(THEME.text);

  items.forEach((it, index) => {
    if (y > 260) { doc.addPage(); y = 20; }

    if (index % 2 === 0) {
      doc.setFillColor(THEME.accent);
      doc.rect(15, y, 180, 8, 'F');
    }

    const name = it.productName || it.name || '';
    const qty = Number(it.quantity);
    const price = Number(it.price || it.unitPrice);
    const total = qty * price;
    const displayName = name.length > 45 ? name.substring(0, 42) + '...' : name;

    doc.text(displayName, cols.desc.x + 2, y + 5.5);
    doc.text(String(qty), cols.qty.x, y + 5.5, { align: 'center' });
    doc.text(formatCurrency(price).replace('PHP', ''), cols.price.x, y + 5.5, { align: 'right' });
    doc.text(formatCurrency(total).replace('PHP', ''), cols.total.x, y + 5.5, { align: 'right' });

    const serials = it.serialNumbers || it.serial_numbers || [];
    if (serials.length > 0) {
      y += 5;
      doc.setFontSize(7);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(THEME.lightText);
      doc.text(`SN: ${serials.join(', ')}`, cols.desc.x + 5, y + 5.5);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(THEME.text);
      y += 3;
    }

    y += 8;
  });

  y += 5;

  // 4. Totals
  const totalBoxX = 120;
  const totalBoxW = 75;
  
  doc.setDrawColor(THEME.line);
  doc.line(15, y, 195, y); 
  y += 5;

  const drawTotalLine = (label, value, isBold = false, isGrand = false) => {
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setFontSize(isGrand ? 12 : 10);
    doc.setTextColor(isGrand ? THEME.primary : THEME.text);
    
    doc.text(label, totalBoxX, y + 5);
    doc.text(value, 195, y + 5, { align: 'right' });
    y += isGrand ? 10 : 6;
  };

  drawTotalLine('Subtotal:', formatCurrency(totalAmount));
  
  if (tenderedAmount > 0 && paymentMethod === 'Cash') {
    drawTotalLine('Cash Tendered:', formatCurrency(tenderedAmount));
    drawTotalLine('Change:', formatCurrency(changeAmount));
  }

  y += 2;
  doc.setFillColor(THEME.primary);
  doc.rect(totalBoxX - 5, y, totalBoxW + 5, 10, 'F');
  doc.setTextColor(THEME.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('TOTAL', totalBoxX, y + 7);
  doc.text(formatCurrency(totalAmount), 195, y + 7, { align: 'right' });

  const footerY = 280;
  doc.setFontSize(8);
  doc.setTextColor(THEME.lightText);
  doc.setFont('helvetica', 'normal');
  doc.text('Thank you for your business!', pageWidth / 2, footerY, { align: 'center' });
  doc.text('Returns accepted within 7 days with receipt.', pageWidth / 2, footerY + 4, { align: 'center' });

  return doc;
};